export const LOADING_DOCUMENT = "LOADING_DOCUMENT";
export const ADD_DOCUMENT = "ADD_DOCUMENT";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const ERROR_DOCUMENT = "ERROR_DOCUMENT";
