export const CREATE_FOLDER = "CREATE_FOLDER";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const ERROR_FOLDER = "ERROR_FOLDER";
export const FETCH_FOLDER = "FETCH_FOLDER";
export const LOADING_FOLDER = "LOADING_FOLDER";
export const UPDATE_PARENT_FOLDER = "UPDATE_PARENT_FOLDER";
export const UPDATE_CHILD_FOLDER = "UPDATE_CHILD_FOLDER";

export const SET_ACTIVE_FOLDER_ID = "SET_ACTIVE_FOLDER_ID";
