export const LOADING_NOTIFICATION = "LOADING_NOTIFICATION";
export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
