export const CREATE_TEAM = 'CREATE_TEAM'
export const EDIT_TEAM = 'EDIT_TEAM'
export const FETCH_TEAM = 'FETCH_TEAM'
export const LOADING_TEAM = 'LOADING_TEAM'
export const DELETE_TEAM = 'DELETE_TEAM'
export const ERROR_TEAM = 'ERROR_TEAM'

export const LOADING_ACCEPTED_TEAM = 'LOADING_ACCEPTED_TEAM'
export const FETCH_ACCEPTED_TEAM = 'FETCH_ACCEPTED_TEAM'
export const EDIT_ACCEPTED_TEAM = 'EDIT_ACCEPTED_TEAM'
export const ERROR_ACCEPTED_TEAM = 'ERROR_ACCEPTED_TEAM'

export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER'
export const DELETE_TEAM_MEMBER = 'DELETE_TEAM_MEMBER'

export const SELECT_ACCEPTED_TEAM_ID = 'SELECT_ACCEPTED_TEAM_ID'
