export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL'

export const FETCH_TEAM_REQUEST = 'FETCH_TEAM_REQUEST'
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const FETCH_TEAM_FAIL = 'FETCH_TEAM_FAIL'

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST'
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL'

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL'

export const CREATE_TEAM = 'CREATE_TEAM'
export const EDIT_TEAM = 'EDIT_TEAM'
export const FETCH_TEAM = 'FETCH_TEAM'
export const LOADING_TEAM = 'LOADING_TEAM'
export const DELETE_TEAM = 'DELETE_TEAM'
export const ERROR_TEAM = 'ERROR_TEAM'
