export const LOADING_USER = 'LOADING_USER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER = 'USER_REGISTER'
export const ERROR_USER = 'ERROR_USER'
